### PR TITLE
Fix issue#1 - Add an option to indicate that this is a tag that shoul…

### PR DESCRIPTION
**Pull request by quanah**
…d be used for the parent and all submodule checkouts

### CODE REVIEW

**Comment by chrismaes87** [comment]
Hello @quanah  and thanks for your contribution. I see how this will work for your use-case. What puzzles me though is this: how come that - at checkout - the head of your submodules is not already at the correct hash (where the tag is)? Normally all correct references should be committed in your master repository, so there should be no need to pass that reference (tag) to all the submodules.

To verify this: move into each of your submodules and `git checkout <tag>`, then see in your master  repository if there are changes. If there are change, I think you should commit them before applying that tag to your master repository.

**Comment by quanah** [comment]
I'm not working from a checkout of the tag, I'm working from a generalized checkout.  This allows me to pull together a source only tarball of any release, regardless of where my repo is at currently.

**Comment by chrismaes87** [comment]
ok I see. I'm leaving for vacation very soon so I won't have time to review this in depth, but I plan on taking a look at this more closely afterwards.

**Comment by quanah** [comment]
Sure no worries!  Thanks for considering it. :)

**Comment by chrismaes87** [comment]
Some remarks:

- you are presupposing that the tag is correctly set on all the correct commits in the submodules, that suits your case, but could result in very strange behavior for other users.
- I think it should be possible to extract the exact commit has for every submodule and pass that information. There would be no need for an extra parameter then.

So I think this should be reworked differently.

**Pull request closed without merging**
